import type { HomeContent } from "@/lib/types";

export const homeContent: HomeContent = {
  meta: {
    issuer: "VENA DIGITAL",
    dateLabel: "FEBRERO 2026",
    projectTitle: "Agente de Atención al cliente ⎢WhatsApp",
    projectSubtitle: "Centro Deportivo Alejandro Falla · Tenis & Pádel",
    version: "Entregable 01 · v2",
  },
  hero: {
    intro: "",
    primaryCtaLabel: "Ver contenido",
    primaryCtaHref: "#contenido",
    secondaryCtaLabel: "Ir al diagnóstico",
    secondaryCtaHref: "/secciones/diagnostico",
  },
  contentIndex: [
    {
      id: 1,
      slug: "diagnostico",
      title: "Diagnóstico As-Is",
      summary:
        "Equipo, sistemas, flujo de reservas, tarifas, brechas y discrepancias",
      theme: "risk",
      status: "in-progress",
      anchorId: "preview-diagnostico",
    },
    {
      id: 2,
      slug: "oportunidades",
      title: "Oportunidades de Mejora",
      summary: "12 oportunidades en P1/P2/P3",
      theme: "opportunity",
      status: "planned",
      anchorId: "preview-oportunidades",
    },
    {
      id: 3,
      slug: "scope",
      title: "Scope del Agente",
      summary: "Alcance, modos, intenciones y mapa de escalamientos",
      theme: "scope",
      status: "planned",
      anchorId: "preview-scope",
    },
    {
      id: 4,
      slug: "flujos",
      title: "Flujos de Conversación",
      summary: "Desarrollo detallado de los 8 flujos del agente",
      theme: "flow",
      status: "planned",
      anchorId: "preview-flujos",
    },
    {
      id: 5,
      slug: "reglas",
      title: "Reglas de Negocio",
      summary: "Reglas críticas de tiempo, profesores y precios",
      theme: "rules",
      status: "ready",
      anchorId: "preview-reglas",
    },
    {
      id: 6,
      slug: "limitaciones",
      title: "Limitaciones Técnicas",
      summary: "Dependencias, operación fuera de horario y condiciones",
      theme: "tech",
      status: "ready",
      anchorId: "preview-limitaciones",
    },
    {
      id: 7,
      slug: "prompt",
      title: "Prompt del Agente",
      summary: "Identidad, reglas codificadas y tarifario completo",
      theme: "prompt",
      status: "ready",
      anchorId: "preview-prompt",
    },
    {
      id: 8,
      slug: "decisiones",
      title: "Decisiones Pendientes",
      summary: "Preguntas abiertas para validación de gerencia",
      theme: "decision",
      status: "ready",
      anchorId: "preview-decisiones",
    },
  ],
  sectionPreviews: [
    {
      slug: "diagnostico",
      headline: "Así opera el centro hoy",
      highlights: [
        "Levantamiento manual basado en entrevistas con Luisa y Willy",
        "Sin integración entre EasyCancha, Excel, Sigo y WhatsApp",
        "Brechas críticas: cobertura 24/7, dependencia de Willy y errores en registros",
      ],
      visualSpec: "mini-table",
    },
    {
      slug: "oportunidades",
      headline: "12 mejoras priorizadas por impacto operativo",
      highlights: [
        "5 oportunidades P1 con efecto directo en ingresos y continuidad",
        "4 oportunidades P2 para eficiencia administrativa y escalabilidad",
        "3 oportunidades P3 para diferenciación y crecimiento",
      ],
      visualSpec: "priority-bars",
    },
    {
      slug: "scope",
      headline: "Qué hace el agente y qué debe escalar",
      highlights: [
        "Reservas, cancelaciones y consultas de precios/promociones",
        "Información inicial de academias con escalamiento a Willy",
        "Excepciones, quejas y casos especiales van a humano",
      ],
      visualSpec: "scope-split",
    },
    {
      slug: "flujos",
      headline: "8 conversaciones modeladas paso a paso",
      highlights: [
        "Secuencia de preguntas, validaciones y respuestas",
        "Condiciones de bifurcación por deporte, horario y tipo de solicitud",
        "Momentos exactos de escalamiento y cierre",
      ],
      visualSpec: "flow-map",
    },
    {
      slug: "reglas",
      headline: "Reglas críticas que el agente no puede ignorar",
      highlights: [
        "Anticipación mínima y límites operativos por tipo de reserva",
        "Restricciones por profesor, horarios y condiciones especiales",
        "Políticas de precio y aplicación consistente de excepciones",
      ],
      visualSpec: "rule-grid",
    },
    {
      slug: "limitaciones",
      headline: "Dependencias técnicas y condiciones de operación",
      highlights: [
        "Dependencia de API de EasyCancha y WhatsApp Business API",
        "Operación fuera de horario y límites de automatización",
        "Condiciones de contingencia para información no confirmada",
      ],
      visualSpec: "dependency-list",
    },
    {
      slug: "prompt",
      headline: "Luisa: identidad y reglas codificadas del agente",
      highlights: [
        "Prompt completo con conocimiento del centro y personalidad",
        "Reglas críticas, flujos y criterios de escalamiento integrados",
        "Tarifario y restricciones como parte del comportamiento del agente",
      ],
      visualSpec: "agent-card",
    },
    {
      slug: "decisiones",
      headline: "Preguntas abiertas que bloquean autonomía completa",
      highlights: [
        "Definiciones pendientes de tarifas de pádel en fines de semana",
        "Criterios para oferta de Willy como entrenador",
        "Reglas de oferta estándar vs bajo solicitud para casos especiales",
      ],
      visualSpec: "decision-list",
    },
  ],
  roadmap: [
    { slug: "diagnostico", label: "Diagnóstico", order: 1, status: "in-progress" },
    { slug: "oportunidades", label: "Oportunidades", order: 2, status: "planned" },
    { slug: "scope", label: "Scope", order: 3, status: "planned" },
    { slug: "flujos", label: "Flujos", order: 4, status: "planned" },
    { slug: "reglas", label: "Reglas", order: 5, status: "ready" },
    { slug: "limitaciones", label: "Limitaciones", order: 6, status: "ready" },
    { slug: "prompt", label: "Prompt", order: 7, status: "ready" },
    { slug: "decisiones", label: "Decisiones", order: 8, status: "ready" },
  ],
};
